# Generated by Django 3.2.5 on 2021-07-28 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='images/')),
                ('mission', models.CharField(max_length=200)),
                ('vision', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Booking name')),
                ('num', models.CharField(default='K100', max_length=10, verbose_name='Booking Number')),
                ('time', models.DateTimeField(verbose_name='Booking Departure Time')),
                ('brief', models.TextField(max_length=300, verbose_name='Booking Information')),
                ('slots', models.IntegerField(default=0, verbose_name='Remaining slots')),
            ],
            options={
                'verbose_name': 'Booking Information',
                'verbose_name_plural': 'Booking Information',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'This is available'), (2, 'Taken by someone'), (3, 'taken by someone'), (4, 'not available anymore')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_class', models.PositiveIntegerField()),
                ('business_class', models.PositiveIntegerField()),
                ('events', models.CharField(max_length=300)),
                ('booK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jh.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Dinning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaze_house', models.PositiveIntegerField()),
                ('artisan', models.PositiveIntegerField()),
                ('gallery', models.CharField(max_length=20)),
                ('bar', models.TextField()),
                ('booK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jh.booking')),
            ],
        ),
    ]
