# Generated by Django 3.2.5 on 2021-07-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jh', '0002_about_booking_contact_dinning_meeting_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='mission',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision',
            field=models.TextField(),
        ),
    ]
