# Generated by Django 3.2.5 on 2021-07-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jh', '0003_auto_20210728_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='business_class',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='events',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='first_class',
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'This is available'), (2, 'slot available'), (3, 'you can book')], default=1),
        ),
    ]
