# Generated by Django 3.2.5 on 2021-07-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jh', '0004_auto_20210728_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'first_class'), (2, 'slot available'), (3, 'events')], default=1),
        ),
    ]
