# Generated by Django 3.2.5 on 2021-07-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jh', '0005_alter_meeting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='num',
            field=models.CharField(default='Ksh.5000', max_length=10, verbose_name='Booking Number'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'first_class'), (2, 'business_class'), (3, 'events')], default=1),
        ),
    ]
