# Generated by Django 3.2.5 on 2021-07-28 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jh', '0008_meeting_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinning',
            name='bar',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dinning',
            name='booK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jh.booking'),
        ),
        migrations.AlterField(
            model_name='dinning',
            name='gallery',
            field=models.PositiveIntegerField(),
        ),
    ]
