# Generated by Django 3.2.5 on 2021-07-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jh', '0009_auto_20210728_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='num',
            field=models.CharField(default='Ksh.5000', max_length=10, verbose_name='Booking Amount'),
        ),
    ]
