# Generated by Django 3.2.5 on 2021-07-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jh', '0010_alter_booking_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='status',
            new_name='select',
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.DateTimeField(verbose_name='Booking Arrival Time'),
        ),
    ]
