# Generated by Django 3.2.5 on 2021-07-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jh', '0012_alter_about_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='booK',
            new_name='book',
        ),
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
