# Generated by Django 3.2.5 on 2021-07-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jh', '0014_alter_room_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='select',
            field=models.PositiveSmallIntegerField(choices=[('superior', 'superior'), ('Superior_room', 'Superior room'), ('Executive_room', 'Executive room'), ('Junior_room', 'Junior room'), ('Presidential_room', 'Presidential Suite')], default='Superior_room'),
        ),
    ]
