# Generated by Django 3.2.5 on 2021-07-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jh', '0015_alter_room_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='select',
            field=models.PositiveSmallIntegerField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('DECEMBER', 'December')]),
        ),
    ]
