# Generated by Django 3.2.5 on 2021-07-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jh', '0016_alter_room_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='select',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Superior room'), (2, 'Executive room'), (3, 'Junior room'), (4, 'Presidential Suite')], default=1),
        ),
    ]
