# Generated by Django 3.2.5 on 2021-07-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jh', '0018_alter_room_select'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='select',
            new_name='room_type',
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'RM1'), (2, 'RM2'), (3, 'RM3'), (4, 'RM4')], default=1),
        ),
    ]
