# Generated by Django 3.2.5 on 2021-07-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jh', '0019_auto_20210729_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinning',
            name='artisan',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dinning',
            name='bar',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dinning',
            name='gallery',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dinning',
            name='gaze_house',
            field=models.CharField(max_length=200),
        ),
    ]
