# Generated by Django 3.2.5 on 2021-07-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jh', '0020_auto_20210729_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.PositiveSmallIntegerField(choices=[('RM1', 'Superior room'), (2, 'Executive room'), (3, 'Junior room'), (4, 'Presidential Suite'), (4, 'Kings Suite')], default='RM1'),
        ),
    ]
